### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [kempniu/kodivc#5]
[The variable "exit_flag"](https://github.com/kempniu/kodivc/blob/4cb9a2a4dc9c5cc26a916ff182fe16699f954b61/kodivc.c#L171 "Update candidate") should [use the data type "sig_atomic_t"](https://www.securecoding.cert.org/confluence/display/seccode/SIG31-C.+Do+not+access+shared+objects+in+signal+handlers "Do not access shared objects in signal handlers.").

**Comment by kempniu** [comment]
While it's a purely cosmetic change (all we ever do with this variable is flip a single bit in it), I'm inclined to agree. It won't hurt to fix this.

**Comment by elfring** [comment]
Thanks for your small source code improvement.
