### ISSUE TITLE
apt-get update issue

### ISSUE THREAD

**Issue by IIIdefconIII** [kempniu/kodivc#8]
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/kempniu/kodivc/ubuntu zesty Release' does not have a Release file.
**N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.**
E: Failed to fetch http://ppa.launchpad.net/kempniu/kodivc/ubuntu/dists/zesty/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by IIIdefconIII** [comment]
iiidefconiii@htpc:~/kodivc-master$ sudo apt-get -y install kodivc
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package kodivc

**Comment by IIIdefconIII** [comment]
using git make: error too

iiidefconiii@htpc:~/kodivc-master/kodivc$ sudo make
gcc -g -o kodivc kodivc.c -DGITVERSION=\"`git log --oneline 2>/dev/null | cut -d' ' -f1 | head -1`\" -DMODELDIR=\"`pkg-config --variable=modeldir pocketsphinx`\" `pkg-config --cflags --libs pocketsphinx sphinxbase` -lcurl
Package pocketsphinx was not found in the pkg-config search path.
Perhaps you should add the directory containing `pocketsphinx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pocketsphinx' found
Package pocketsphinx was not found in the pkg-config search path.
Perhaps you should add the directory containing `pocketsphinx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pocketsphinx' found
Package sphinxbase was not found in the pkg-config search path.
Perhaps you should add the directory containing `sphinxbase.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sphinxbase' found
kodivc.c:28:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by IIIdefconIII** [comment]
trying the git version: 

iiidefconiii@htpc:~/kodivc-master/kodivc$ sudo apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
^[[Acurl is already the newest version (7.52.1-4ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
iiidefconiii@htpc:~/kodivc-master/kodivc$ make
gcc -g -o kodivc kodivc.c -DGITVERSION=\"`git log --oneline 2>/dev/null | cut -d' ' -f1 | head -1`\" -DMODELDIR=\"`pkg-config --variable=modeldir pocketsphinx`\" `pkg-config --cflags --libs pocketsphinx sphinxbase` -lcurl
Package pocketsphinx was not found in the pkg-config search path.
Perhaps you should add the directory containing `pocketsphinx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pocketsphinx' found
Package pocketsphinx was not found in the pkg-config search path.
Perhaps you should add the directory containing `pocketsphinx.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pocketsphinx' found
Package sphinxbase was not found in the pkg-config search path.
Perhaps you should add the directory containing `sphinxbase.pc'
to the PKG_CONFIG_PATH environment variable
No package 'sphinxbase' found
kodivc.c:28:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by IIIdefconIII** [comment]
I got the answer. I installed ibcurl4-gnutls-dev and it is done.
but now stuck on   #include <sphinxbase/ad.h>

proberly some sudo-apt get also to resolve this, i need to figure out which one

**Comment by IIIdefconIII** [comment]
did all of this

sudo apt-get install git
sudo apt-get install automake
sudo apt-get install libtool
sudo apt-get install bison
sudo apt-get install python-dev
sudo apt-get install swig
sudo apt-get install make
sudo apt-get install pkg-config
git clone https://github.com/cmusphinx/sphinxbase.git
cd sphinxbase
./autogen.sh
make
sudo make install
cd ..
git clone git://github.com/cmusphinx/pocketsphinx.git
cd pocketsphinx
./autogen.sh
make
sudo make install
cd ..

still stuck on #include <sphinxbase/ad.h>

**Comment by IIIdefconIII** [comment]
could you please help me with the installation

**Comment by IIIdefconIII** [comment]
sry for spamming, i reinstall the cmu and that part is working

used the steps over here:
http://cmusphinx.sourceforge.net/wiki/tutorialpocketsphinx

but still getting a error when trying to make it..

iiidefconiii@htpc:~/Downloads/kodivc$ make
gcc -g -o kodivc kodivc.c -DGITVERSION=\"`git log --oneline 2>/dev/null | cut -d' ' -f1 | head -1`\" -DMODELDIR=\"`pkg-config --variable=modeldir pocketsphinx`\" `pkg-config --cflags --libs pocketsphinx sphinxbase` -lcurl
kodivc.c:32:32: fatal error: sphinxbase/cont_ad.h: No such file or directory
 #include <sphinxbase/cont_ad.h>
                                ^
compilation terminated.
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 1

also tried
      export LD_LIBRARY_PATH=/usr/local/lib/python2.7/dist-packages/sphinxbase

no avail

**Comment by kempniu** [comment]
Ubuntu started using version 5prealpha of Pocketsphinx in 16.04 (Xenial).  Sadly, that version removed the continuous listening API used by kodivc.  There is another one available, but I am unlikely to find time in the foreseeable future to migrate kodivc to it.

As for the apt-get issue you are experiencing, the PPA does not contain packages for anything later than Ubuntu 15.04 (Vivid). The reason for that is the same problem you are facing when trying to build kodivc from source.

I will leave this issue open, because it is a valid problem, though please do not count on it getting resolved any time soon.  If you are really interested in trying kodivc out, please use an older Pocketsphinx version (0.6-0.8).

**Comment by IIIdefconIII** [comment]
after i installed succesfully 0.8 im getting the following error:

INFO: Initializing, please wait...
CRITICAL: Unable to connect to Kodi running at localhost:8080

i can connect to the web server from any local pc just fine, so im not sure whats going wrong, feeling so close, yet so far.

i dont see anyhting in the logs

**Comment by IIIdefconIII** [comment]
got it finally up and running, thanks! only it doesnt reconize me good anoug

any easy guide how to create own actions, like prases watch a random movie or so.
and any mic recommendation, cause it doesnt pick up my words, only when i YELL, i tried several settings and mic recording volumes but no avail till now, tried a logitech quickam mic and a cheap 20 doller lin in mic

**Comment by IIIdefconIII** [comment]
after hours of spending i finally found the issue:

you can report this on the faq page;
To test the quality install audacity and make a record.
Myne sounded like a chipmunck and i started to google.
The answer to my problem was:

pulsegedit /etc/pulse/daemon.conf
insert this into the daemon.conf
default-sample-rate = 16000
pulseaudio --kill && pulseaudio --start

**Comment by IIIdefconIII** [comment]
end of all this is not IT, but thank you for trying,...

**Comment by PraveenkumarDonga** [comment]
hi! IIIdefconIII, 
I am also trying the same, so what was the solution?
had you installed the older version of  Pocketsphinx?
Looking forward for your help?

**Comment by IIIdefconIII** [comment]
did you read the post? the answer is litary said...

pulsegedit /etc/pulse/daemon.conf
insert this into the daemon.conf
default-sample-rate = 16000
pulseaudio --kill && pulseaudio --start

**Comment by jiapei100** [comment]
Yeah.... **PocketSphinx** is the tough one ... Even today... I just tried the **NEWEST** release....
